import { TemplateId } from "@/types/biodata";

export interface TemplateTheme {
  id: TemplateId;
  pageBackground: string;
  /** Solid-color fallback for PDF export, which can't render CSS gradients. */
  pdfBackground: string;
  headerVariant: "standard" | "insetCard" | "portrait";
  frame: "gold-double" | "brown-double" | "temple-band" | "mandala" | "none";
  decoration: "peacock" | "marigold" | "kalamkari" | "deco-corners" | "watercolor" | "none";
  headingColor: string;
  accentColor: string;
  bodyColor: string;
  mutedColor: string;
  badgeBg: string;
  badgeText: string;
  photoRing: string;
  photoBg: string;
  dividerColor: string;
}

export const TEMPLATE_THEMES: Record<string, TemplateTheme> = {
  "royal-rajasthani": {
    id: "royal-rajasthani",
    pageBackground: "#FBF3E7",
    pdfBackground: "#FBF3E7",
    headerVariant: "standard",
    frame: "brown-double",
    decoration: "none",
    headingColor: "#7A1F3D",
    accentColor: "#A8863A",
    bodyColor: "#4A3F34",
    mutedColor: "#A8863A",
    badgeBg: "#F3E4C8",
    badgeText: "#7A1F3D",
    photoRing: "#A8863A",
    photoBg: "#F0DCC0",
    dividerColor: "#A8863A",
  },
  "elegant-ivory-gold": {
    id: "elegant-ivory-gold",
    pageBackground: "#FDFBF6",
    pdfBackground: "#FDFBF6",
    headerVariant: "standard",
    frame: "none",
    decoration: "none",
    headingColor: "#3A332B",
    accentColor: "#B8912A",
    bodyColor: "#4A3F34",
    mutedColor: "#9C917F",
    badgeBg: "#F3E4B8",
    badgeText: "#9C7A1F",
    photoRing: "#C9A227",
    photoBg: "#F5EEDD",
    dividerColor: "#C9A227",
  },
  professional: {
    id: "professional",
    pageBackground: "#F7F8FA",
    pdfBackground: "#F7F8FA",
    headerVariant: "standard",
    frame: "none",
    decoration: "none",
    headingColor: "#2C3E52",
    accentColor: "#2C3E52",
    bodyColor: "#3F4A57",
    mutedColor: "#8494A3",
    badgeBg: "#E8ECF1",
    badgeText: "#2C3E52",
    photoRing: "#3F5771",
    photoBg: "#E8ECF1",
    dividerColor: "#3F5771",
  },
  "pastel-contemporary": {
    id: "pastel-contemporary",
    pageBackground: "linear-gradient(160deg,#FCEFE9,#F3F6EE)",
    pdfBackground: "#F8EFE9",
    headerVariant: "standard",
    frame: "none",
    decoration: "none",
    headingColor: "#5A4E45",
    accentColor: "#8A9E7E",
    bodyColor: "#5A4E45",
    mutedColor: "#A9998C",
    badgeBg: "#E4EDE2",
    badgeText: "#3C5640",
    photoRing: "#8A9E7E",
    photoBg: "#F3E4DC",
    dividerColor: "#8A9E7E",
  },
  "peacock-motif": {
    id: "peacock-motif",
    pageBackground: "radial-gradient(circle at 12% 8%,#0F6B5C,#0A4A40 55%,#083A32 100%)",
    pdfBackground: "#0A4A40",
    headerVariant: "standard",
    frame: "gold-double",
    decoration: "peacock",
    headingColor: "#FBF3D8",
    accentColor: "#D9B84A",
    bodyColor: "#EDE3C4",
    mutedColor: "#B8A876",
    badgeBg: "rgba(217,184,74,.16)",
    badgeText: "#F3E9C9",
    photoRing: "#D9B84A",
    photoBg: "rgba(217,184,74,.15)",
    dividerColor: "#D9B84A",
  },
  "marigold-vermilion": {
    id: "marigold-vermilion",
    pageBackground: "#FFF7ED",
    pdfBackground: "#FFF7ED",
    headerVariant: "standard",
    frame: "none",
    decoration: "marigold",
    headingColor: "#9A3B12",
    accentColor: "#C77531",
    bodyColor: "#6B4526",
    mutedColor: "#C77531",
    badgeBg: "#FBE0C7",
    badgeText: "#9A3B12",
    photoRing: "#E2661B",
    photoBg: "#FBE0C7",
    dividerColor: "#E2661B",
  },
  "kalamkari-print": {
    id: "kalamkari-print",
    pageBackground: "#F4ECDC",
    pdfBackground: "#F4ECDC",
    headerVariant: "standard",
    frame: "brown-double",
    decoration: "kalamkari",
    headingColor: "#5C3A1E",
    accentColor: "#8B4A2B",
    bodyColor: "#4A3520",
    mutedColor: "#8B7355",
    badgeBg: "#E4D2B0",
    badgeText: "#5C3A1E",
    photoRing: "#8B4A2B",
    photoBg: "#E4D2B0",
    dividerColor: "#2E4057",
  },
  "sacred-mandala": {
    id: "sacred-mandala",
    pageBackground: "#FFF8ED",
    pdfBackground: "#FFF8ED",
    headerVariant: "standard",
    frame: "mandala",
    decoration: "none",
    headingColor: "#7A4A12",
    accentColor: "#C77B2C",
    bodyColor: "#5C4526",
    mutedColor: "#B8935E",
    badgeBg: "#FBE7C7",
    badgeText: "#7A4A12",
    photoRing: "#C77B2C",
    photoBg: "#FBE7C7",
    dividerColor: "#C77B2C",
  },
  "south-indian-temple": {
    id: "south-indian-temple",
    pageBackground: "#FBF1E7",
    pdfBackground: "#FBF1E7",
    headerVariant: "standard",
    frame: "temple-band",
    decoration: "none",
    headingColor: "#7A1526",
    accentColor: "#7A1526",
    bodyColor: "#4A3F34",
    mutedColor: "#9C7A1F",
    badgeBg: "#F3E4B8",
    badgeText: "#7A1526",
    photoRing: "#7A1526",
    photoBg: "#F0DCC0",
    dividerColor: "#9C7A1F",
  },
  "bengali-alpana": {
    id: "bengali-alpana",
    pageBackground: "#8E1B2C",
    pdfBackground: "#8E1B2C",
    headerVariant: "insetCard",
    frame: "none",
    decoration: "none",
    headingColor: "#8E1B2C",
    accentColor: "#B3543F",
    bodyColor: "#5A3028",
    mutedColor: "#B3543F",
    badgeBg: "#F3D9D9",
    badgeText: "#8E1B2C",
    photoRing: "#8E1B2C",
    photoBg: "#F3D9D9",
    dividerColor: "#B3543F",
  },
  "photo-forward": {
    id: "photo-forward",
    pageBackground: "#22201D",
    pdfBackground: "#22201D",
    headerVariant: "portrait",
    frame: "none",
    decoration: "none",
    headingColor: "#FBF7EE",
    accentColor: "#C9BFB2",
    bodyColor: "#E4DED6",
    mutedColor: "#9C917F",
    badgeBg: "rgba(255,255,255,.1)",
    badgeText: "#FBF7EE",
    photoRing: "#9C917F",
    photoBg: "#4A4340",
    dividerColor: "#4A4340",
  },
  "floral-watercolor": {
    id: "floral-watercolor",
    pageBackground: "#FFFDFB",
    pdfBackground: "#FFFDFB",
    headerVariant: "standard",
    frame: "none",
    decoration: "watercolor",
    headingColor: "#7A5468",
    accentColor: "#A17E96",
    bodyColor: "#5A4A54",
    mutedColor: "#A17E96",
    badgeBg: "#F6E4EA",
    badgeText: "#7A5468",
    photoRing: "#D9A9C0",
    photoBg: "#F6E4EA",
    dividerColor: "#D9A9C0",
  },
  "indo-deco": {
    id: "indo-deco",
    pageBackground: "#12141A",
    pdfBackground: "#12141A",
    headerVariant: "standard",
    frame: "none",
    decoration: "deco-corners",
    headingColor: "#F3E4B8",
    accentColor: "#C9A227",
    bodyColor: "#D9CFB8",
    mutedColor: "#8A8470",
    badgeBg: "rgba(201,162,39,.15)",
    badgeText: "#F3E4B8",
    photoRing: "#C9A227",
    photoBg: "rgba(201,162,39,.18)",
    dividerColor: "#C9A227",
  },
};
